import { ArrowRight, LockKeyhole, ShieldCheck, Spade } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';

const games = [
  { type: 'poker', name: 'Texas Hold’em Poker', count: '2–9 players', summary: 'No-limit tournament poker with blinds, all-ins, side pots, and private hole cards.', icon: '♠' },
  { type: 'blackjack', name: 'Multiplayer Blackjack', count: '1–7 players', summary: 'Play together against an automatic server dealer with splits, doubles, insurance, and surrender.', icon: 'A' },
] as const;

export function HomePage(): ReactNode {
  return <main><section className="relative overflow-hidden px-4 pb-14 pt-16 sm:pb-20 sm:pt-24"><div className="felt-glow" /><div className="relative mx-auto max-w-5xl text-center"><div className="mx-auto mb-6 grid h-14 w-14 place-items-center rounded-2xl border border-gold/30 bg-gold/10 text-gold"><Spade size={26} /></div><p className="mb-3 text-xs font-semibold uppercase tracking-[.3em] text-gold">Private tables for your people</p><h1 className="font-serif text-4xl font-semibold tracking-tight text-cream sm:text-6xl">Cards with friends,<br />minus the noise.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-muted sm:text-lg">Create a room, share one code, and play a server-authoritative game from any device. No accounts, public matchmaking, or real-money features.</p><div className="mt-8 flex flex-wrap justify-center gap-4 text-sm text-gray-300"><span className="feature-pill"><LockKeyhole size={15} /> Password-ready private rooms</span><span className="feature-pill"><ShieldCheck size={15} /> Reconnect-safe seats</span></div></div></section><section className="mx-auto grid max-w-6xl gap-5 px-4 pb-20 md:grid-cols-2">{games.map((game) => <article key={game.type} className="group rounded-3xl border border-white/10 bg-panel p-6 shadow-card transition hover:-translate-y-1 hover:border-gold/30 sm:p-8"><div className="mb-8 flex items-start justify-between"><div className="grid h-14 w-12 place-items-center rounded-xl bg-cream font-serif text-2xl font-bold text-ink shadow-card">{game.icon}</div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-muted">{game.count}</span></div><h2 className="font-serif text-2xl font-semibold text-cream">{game.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-muted">{game.summary}</p><div className="mt-7 grid gap-2 sm:grid-cols-2"><Link to={`/create/${game.type}`} className="button-primary">Create private room <ArrowRight size={16} /></Link><Link to={`/join?game=${game.type}`} className="button-secondary">Join room</Link></div></article>)}</section><section className="border-y border-white/5 bg-black/10 px-4 py-10 text-center"><p className="font-medium text-cream">Play-money only — no cash value.</p><p className="mt-2 text-sm text-muted">No deposits, withdrawals, purchasable chips, cryptocurrency, or public player pool.</p></section></main>;
}
