import { ArrowLeft, LockKeyhole } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useGame } from '../game-context.js';
import { Button, Field, Input, Panel } from '../components/ui.js';

export function CreatePage(): ReactNode {
  const gameType = useParams().game === 'blackjack' ? 'blackjack' : 'poker'; const navigate = useNavigate(); const { createRoom } = useGame();
  const [name, setName] = useState(''); const [password, setPassword] = useState(''); const [count, setCount] = useState(gameType === 'poker' ? 4 : 3); const [balance, setBalance] = useState(gameType === 'poker' ? 10_000 : 1_000); const [timer, setTimer] = useState(30); const [autoStart, setAutoStart] = useState(false); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent): Promise<void> => {
    event.preventDefault(); setBusy(true);
    const settings = gameType === 'poker'
      ? { turnSeconds: timer, hostGraceSeconds: 30, autoStart, poker: { startingBalance: balance, smallBlind: 50, bigBlind: 100, timedBlindMinutes: 0, pauseBetweenHands: false } }
      : { turnSeconds: timer, hostGraceSeconds: 30, autoStart, blackjack: { startingBalance: balance * 2, minimumBet: 20, maximumBet: 1000, decks: 6, penetrationPercent: 75, resplitAces: false, splitTenValues: false } };
    const result = await createRoom({ displayName: name, ...(password === '' ? {} : { password }), gameType, expectedPlayerCount: count, settings });
    setBusy(false); if (result.ok) void navigate('/room');
  };
  return <SetupShell title={`Create ${gameType === 'poker' ? 'a poker' : 'a blackjack'} room`} subtitle="You’ll be the room coordinator—not the dealer, banker, or arbiter."><form className="grid gap-5" onSubmit={(event) => { void submit(event); }}><Field label="Your display name"><Input value={name} onChange={(event) => setName(event.target.value)} required minLength={1} maxLength={24} autoComplete="nickname" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Expected players"><Input type="number" value={count} min={gameType === 'poker' ? 2 : 1} max={gameType === 'poker' ? 9 : 7} onChange={(event) => setCount(event.target.valueAsNumber)} required /></Field><Field label={gameType === 'poker' ? 'Starting chips' : 'Starting credits'}><Input type="number" value={balance} min={gameType === 'poker' ? 100 : 20} onChange={(event) => setBalance(event.target.valueAsNumber)} required /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Turn timer" hint="10–180 seconds"><Input type="number" value={timer} min={10} max={180} onChange={(event) => setTimer(event.target.valueAsNumber)} required /></Field><Field label="Optional password"><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={4} maxLength={72} autoComplete="new-password" placeholder="Leave blank for code-only" /></Field></div><label className="flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-white/10 bg-black/10 px-4"><input type="checkbox" checked={autoStart} onChange={(event) => setAutoStart(event.target.checked)} className="h-5 w-5 accent-[#d3ad5b]" /><span><span className="block text-sm font-medium">Auto-start when everyone is ready</span><span className="text-xs text-muted">Shows a visible five-second countdown.</span></span></label><Button type="submit" disabled={busy}>{busy ? 'Creating secure room…' : 'Create private room'}</Button></form></SetupShell>;
}

export function JoinPage(): ReactNode {
  const [params] = useSearchParams(); const navigate = useNavigate(); const { joinRoom } = useGame(); const [name, setName] = useState(''); const [code, setCode] = useState((params.get('room') ?? '').toUpperCase()); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent): Promise<void> => { event.preventDefault(); setBusy(true); const result = await joinRoom({ displayName: name, roomCode: code, ...(password === '' ? {} : { password }) }); setBusy(false); if (result.ok) void navigate('/room'); };
  return <SetupShell title="Join a private room" subtitle="Ask your friend for the six-character code and password, if they set one."><form className="grid gap-5" onSubmit={(event) => { void submit(event); }}><Field label="Your display name"><Input value={name} onChange={(event) => setName(event.target.value)} required maxLength={24} autoComplete="nickname" /></Field><Field label="Room code"><Input value={code} onChange={(event) => setCode(event.target.value.toUpperCase().replace(/[^A-Z2-9]/gu, '').slice(0, 6))} required minLength={6} maxLength={6} className="font-mono text-lg uppercase tracking-[.25em]" autoComplete="off" /></Field><Field label="Room password" hint="Leave blank if the host did not set one."><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /></Field><Button type="submit" disabled={busy}>{busy ? 'Joining…' : 'Join room'}</Button></form></SetupShell>;
}

function SetupShell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }): ReactNode { return <main className="mx-auto max-w-2xl px-4 py-10 sm:py-16"><Link to="/" className="mb-6 inline-flex items-center gap-2 text-sm text-muted hover:text-white"><ArrowLeft size={16} /> Back to games</Link><Panel className="p-6 sm:p-8"><div className="mb-7"><div className="mb-4 grid h-10 w-10 place-items-center rounded-xl bg-gold/10 text-gold"><LockKeyhole size={19} /></div><h1 className="font-serif text-3xl font-semibold text-cream">{title}</h1><p className="mt-2 text-sm leading-6 text-muted">{subtitle}</p></div>{children}</Panel></main>; }
